# Generated by Django 5.0.3 on 2024-03-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='phone',
            new_name='phonenumber',
        ),
        migrations.AlterField(
            model_name='receiver',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
