# Generated by Django 5.0.3 on 2024-03-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_rename_phone_receiver_phonenumber_alter_receiver_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiver',
            name='id',
        ),
        migrations.AddField(
            model_name='receiver',
            name='Timestemp',
            field=models.TextField(default='2023-03-22T21:55:38.364Z', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
