# Generated by Django 5.0.3 on 2024-03-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_remove_receiver_id_receiver_timestemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiver',
            name='Timestemp',
        ),
        migrations.AddField(
            model_name='receiver',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
