# Generated by Django 5.0.3 on 2024-03-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0005_alter_receiver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
