# Generated by Django 5.0.3 on 2024-03-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0006_alter_receiver_id_alter_receiver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
